Repository skxlpv/UKDTelegramBot, pull requests merged in 2023-04, with the labels that each got.

#8 WR-1: created worker for scheduling schedule and cleaning database fr…
  bot/database/connection.py
  bot/database/schedule_requests.py
  bot/database/serializers.py
  bot/handlers/cancel_state.py
  bot/handlers/search.py
  bot/handlers/show_schedule.py
  bot/handlers/test_handlers.py
  bot/keyboards/reply/menu_keyboard.py
  bot/utils/__init__.py
  bot/worker/__init__.py
  bot/worker/scheduler.py
  bot/worker/tasks.py
  configs.py
  loader.py
  requirements.txt
  run.py
Labels: feature

#9 Feature/schedule
  bot/handlers/menu.py
  bot/handlers/schedule_answer.py
  bot/handlers/search.py
  bot/handlers/show_schedule.py
  bot/keyboards/inline/schedule_keyboard.py
  bot/keyboards/inline/yes_or_not_keyboard.py
  bot/states/UserStates.py
  bot/utils/schedule_utils.py
  run.py
Labels: bug, feature

#11 Feature/favorites
  bot/database/docs/codes
  bot/handlers/favorites.py
  bot/handlers/menu.py
  bot/handlers/schedule_answer.py
  bot/handlers/search.py
  bot/handlers/show_schedule.py
  bot/handlers/start.py
  bot/handlers/test_handlers.py
  bot/keyboards/reply/course_keyboard.py
  bot/keyboards/reply/favorite_keyboard.py
  bot/keyboards/reply/group_keyboard.py
  bot/states/UserStates.py
  bot/utils/schedule_utils.py
  bot/worker/tasks.py
  run.py
Labels: feature

#12 Fixed database user_id insertion
  bot/handlers/schedule_answer.py
Labels: fix

#13 Feature/worker
  bot/handlers/favorites.py
  bot/handlers/menu.py
  bot/handlers/search.py
  bot/handlers/show_schedule.py
  bot/handlers/start.py
  bot/utils/schedule_utils.py
  bot/worker/tasks.py
Labels: bug, enhancement

#15 Stable version 04.04.23
  bot/database/__init__.py
  bot/database/connection.py
  bot/database/docs/codes
  bot/database/schedule_requests.py
  bot/database/serializers.py
  bot/handlers/favorites.py
  bot/handlers/menu.py
  bot/handlers/restart.py
  bot/handlers/schedule_answer.py
  bot/handlers/search.py
  bot/keyboards/inline/search_keyboard.py
  bot/utils/__init__.py
  bot/utils/render_schedule.py
  bot/utils/schedule_utils.py
  bot/utils/search_utils.py
  bot/worker/tasks.py
Labels: feature

#17 feature/docker + improvements
  Dockerfile
  bot/database/__init__.py
  bot/database/connection.py
  bot/database/docs/codes
  bot/database/schedule_requests.py
  bot/database/serializers.py
  bot/handlers/favorites.py
  bot/handlers/handle_start_error.py
  bot/handlers/schedule_buttons_handler.py
  bot/handlers/search.py
  bot/handlers/settings.py
  bot/handlers/show_schedule.py
  bot/keyboards/inline/schedule_keyboard.py
  bot/keyboards/reply/favorite_keyboard.py
  bot/keyboards/reply/menu_keyboard.py
  bot/keyboards/reply/specialties_keyboard.py
  bot/keyboards/reply/teacher_keyboard.py
  bot/middlewares/cancel_middleware.py
  bot/middlewares/settings_middleware.py
  bot/states/UserStates.py
  bot/utils/render_schedule.py
  bot/utils/schedule_utils.py
  bot/worker/tasks.py
  configs.py
  docker-compose.yml
  run.py
Labels: feature, fix

#18 TR-1: added emoji to show current day, made menu available everywhere…
  bot/handlers/favorites.py
  bot/handlers/menu.py
  bot/handlers/schedule_buttons_handler.py
  bot/handlers/search.py
  bot/handlers/start.py
  bot/keyboards/inline/schedule_keyboard.py
  bot/keyboards/reply/menu_keyboard.py
  bot/utils/schedule_utils.py
  loader.py
Labels: enhancement, feature

#19 Feature/settings
  .env.dist
  bot/handlers/menu.py
  bot/handlers/settings.py
  bot/handlers/settings_buttons_handler.py
  bot/handlers/start.py
  bot/keyboards/inline/settings_keyboard.py
  bot/middlewares/start_middleware.py
  run.py
Labels: enhancement, feature

#20 Feature/logging
  .gitignore
  bot/database/pref_requests.py
  bot/database/schedule_requests.py
  bot/database/serializers.py
  bot/handlers/favorites.py
  bot/handlers/handle_start_error.py
  bot/handlers/menu.py
  bot/handlers/restart.py
  bot/handlers/schedule_buttons_handler.py
  bot/handlers/search.py
  bot/handlers/settings.py
  bot/handlers/settings_buttons_handler.py
  bot/handlers/start.py
  bot/keyboards/inline/role_keyboard.py
  bot/keyboards/inline/schedule_keyboard.py
  bot/keyboards/inline/search_keyboard.py
  bot/keyboards/inline/settings_keyboard.py
  bot/keyboards/inline/yes_or_not_keyboard.py
  bot/keyboards/reply/menu_keyboard.py
  bot/middlewares/cancel_middleware.py
  bot/storage/placeholders/buttons.py
  bot/storage/placeholders/callbacks.py
  bot/storage/placeholders/messages.py
  bot/utils/__init__.py
  bot/utils/render_schedule.py
  bot/utils/schedule_utils.py
  bot/worker/tasks.py
  loader.py
  run.py
Labels: enhancement, feature, fix

#21 Feature/docker
  .env.dist
  Dockerfile
  bot/database/__init__.py
  bot/handlers/favorites.py
  bot/handlers/help.py
  bot/handlers/search.py
  bot/handlers/settings_buttons_handler.py
  bot/middlewares/help_middleware.py
  bot/storage/placeholders/messages.py
  bot/utils/schedule_utils.py
  configs.py
  docker-compose.yml
  run.py
Labels: enhancement

#22 Fix/emoji
  Dockerfile
  bot/database/docs/codes
  bot/database/schedule_requests.py
  bot/handlers/favorites.py
  bot/handlers/schedule_buttons_handler.py
  bot/handlers/search.py
  bot/handlers/settings_buttons_handler.py
  bot/keyboards/inline/schedule_keyboard.py
  bot/storage/placeholders/messages.py
  bot/utils/__init__.py
  bot/utils/get_today_date.py
  bot/utils/render_schedule.py
  bot/utils/schedule_utils.py
  bot/utils/search_utils.py
  bot/worker/tasks.py
  docker-compose.yml
  loader.py
Labels: fix
